site_name: PySiddhi
site_description: Python Stream Processing and Complex Event Processing Engine
site_author: WSO2
site_url: https://wso2.github.io/PySiddhi/
extra_css:
- stylesheets/extra.css
repo_name: PySiddhi
repo_url: https://github.com/wso2/PySiddhi
copyright: Copyright &copy; 2011 - 2018 WSO2
theme:
  logo: images/siddhi-logo-w.svg
  palette:
    primary: teal
    accent: teal
  favicon: images/favicon.ico
  name: 'material'
markdown_extensions:
- admonition
- toc(permalink=true)
- codehilite(guess_lang=false)
pages:
  - Welcome to PySiddhi: index.md
  - License: license.md
  - Installation Guide: Installation-Guide.md
  - Run PySiddhi5: Run-PySiddhi5.md
  - Debug PySiddhi5: Debugging-Siddhi-Queries.md
  - Advanced Concepts of PySiddhi: Using-Siddhi-from-Python.md
  - PySiddhi Client for WSO2 Stream Processor:
    - Run PySiddhi Client: Quick-Demo-(SP4).md
    - Client APIs to Manage Siddhi App: Siddhi-App-Management-of-WSO2-SP-4.md
    - Client APIs to Simulate Events: Event-Simulator-of-SP-4.md
