site_name: PySiddhi
site_description: Python Stream Processing and Complex Event Processing Engine
repo_name: PySiddhi
repo_url: https://github.com/siddhi-io/PySiddhi/
edit_uri: https://github.com/siddhi-io/PySiddhi/blob/master/
copyright: Siddhi - Documentation
theme:
  name: material
  logo: images/siddhi-logo.svg
  favicon: images/favicon.ico
  palette:
    primary: teal
    accent: teal
extra_css:
  - assets/stylesheets/extra.css
extra_javascript:
  - assets/javascripts/extra.js
extra:
  social:
    - type: github
      link: https://github.com/siddhi-io/siddhi
    - type: medium
      link: https://medium.com/siddhi-io
    - type: twitter
      link: https://twitter.com/siddhi_io
    - type: linkedin
      link: https://www.linkedin.com/groups/13553064
google_analytics:
  - UA-103065-28
  - auto
markdown_extensions:
  - markdown.extensions.admonition
pages:
  - Information: index.md
  - Installation Guide: Installation-Guide.md
      - Run PySiddhi: Run-PySiddhi.md
      - Debug PySiddhi: Debugging-Siddhi-Queries.md
      - Advanced Concepts of PySiddhi: Using-Siddhi-from-Python.md
      - PySiddhi Client for WSO2 Stream Processor:
          - Run PySiddhi Client: Quick-Demo-(SP4).md
          - Client APIs to Manage Siddhi App: Siddhi-App-Management-of-WSO2-SP-4.md
          - Client APIs to Simulate Events: Event-Simulator-of-SP-4.md
  - License: license.md

